### ISSUE TITLE
Create a Splash Screen

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/MovieDroid#11] opened 2022-03-29 17:22 UTC
Create a splash screen for the app

One of the ways of implementing a splash screen:-
https://stackoverflow.com/a/5486970/17369066

It is preferrable to make a design for the splash screen in figma before implementing it in xml

**Comment by karanpreet8082** [comment] 2022-04-02 09:47
I would like to work on this issue.
Let’s put our heads/minds together.

**Comment by yellowHatpro** [comment] 2022-04-02 09:47
> I would like to work on this issue. Let’s put our heads/minds together.

Ya sure why not 😄

**Comment by karanpreet8082** [comment] 2022-04-02 09:49
Thank you sir very much for giving me a chance to showcase my skills.

**Comment by vishal2376** [comment] 2022-10-01 06:58
Hi, I would like to work on this issue.

I can create a splash screen with implementation in kotlin.

**Comment by yellowHatpro** [comment] 2022-10-01 08:10
Hello @vishal2376, thanks for your interest. Currently the issue is assigned to @karanpreet8082 , but you are free to explore other issues 😀✨

**Comment by Perumallpardhiv** [comment] 2022-10-05 19:29
@yellowHatpro Can I contribute on this issue?

**Closed as completed** 2022-10-06 16:02 UTC
Labels: enhancement, help wanted, hacktoberfest
